library:
  source-dirs: src
tests:
  Parser-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Parser
      - hspec >= 2.7.1
      - QuickCheck >= 2.13.2
      - transformers >= 0.5.6.2
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
  - lens
  - bytestring
  - base >= 4.7 && < 5
  - containers >= 0.6.0
  - transformers >= 0.5.6.2
  - mtl >= 2.2.2
  - wreq >= 0.5.3.2
name: Parser
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Oliver James Cole
github: hive7/Parser
license: BSD3
executables:
  Parser-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Parser
description: Please see the README on GitHub at <https://github.com/hive7/Parser#readme>
